name: Retrieve secrets
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://52.90.108.253:8200
        token: token
        secrets: |
          kv/sas user user ;
