name: Retrieve secrets
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : echo "hai"
    - name: Import Secrets
      id: secrets
      with:
        url: 'http://52.90.108.253:8200/ui/'    # Address of running Vault instance
        method: token
        token: token
        secrets: |
          secret/sas secrets;
