name: Retrieve secrets
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2
      with:
        url: http://52.90.108.253:8200
        token: token
        secrets: |
          /cubbyhole/foo foo ;
    - name: Sensitive Operation
      run: "my-cli --token '${{ steps.secrets.outputs.foo }}'"
