name: Retrieve secrets
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Import Secrets
      uses: hashicorp/vault-action@v1.0.1
      with:
        url: http://52.90.108.253:8200/ui/vault/secrets
        method: token
        token: token
        secrets: |
          kv/sas user
          run - echo " Hai ${{jobs.build.runs-on}}"
